// <auto-generated />
using System;
using System.Collections.Generic;
using Hex.Scaffold.Adapters.Persistence.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hex.Scaffold.Adapters.Persistence.PostgreSql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427135235_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hex.Scaffold.Domain.AccountAggregate.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("AppliedConfigurations")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("applied_configurations");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean")
                        .HasColumnName("closed");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("Dashboard")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("dashboard");

                    b.Property<string>("DefaultsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("defaults");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("FutureRequirementsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("future_requirements");

                    b.Property<string>("IdentityJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("identity");

                    b.Property<bool>("Livemode")
                        .HasColumnType("boolean")
                        .HasColumnName("livemode");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("RequirementsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("requirements");

                    b.HasKey("Id");

                    b.HasIndex("Created", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_accounts_created_id_desc");

                    b.ToTable("accounts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
